name: observable
version: 0.22.1+3
author: Dart Team <misc@dartlang.org>
description: Support for marking objects as observable
homepage: https://github.com/dart-lang/observable
environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'
dependencies:
  collection: '^1.11.0'
  dart_internal: '^0.1.1'
  meta: '^1.0.4'
  quiver: '>=0.24.0 <0.30.0'
dev_dependencies:
  dart_style: '^1.0.9'
  build_runner: ^0.7.11
  build_test: ^0.10.0
  build_web_compilers: ^0.3.1
  test: ^0.12.0
