name: observable
version: 0.20.4+1
author: Dart Team <misc@dartlang.org>
description: Support for marking objects as observable
homepage: https://github.com/dart-lang/observable
environment:
  sdk: '>=1.22.0 <2.0.0'
dependencies:
  collection: '^1.11.0'
  meta: '^1.0.4'
  quiver: '>=0.24.0 <0.26.0'
dev_dependencies:
  test: '^0.12.17'
